multiple user.txt

########################################################################
# Signing user for specified context (cluster,namespace,credential)
# and using `rolebinding --group=...` for group users access control
########################################################################
@ client computer:

## 1.  generate private key
openssl genrsa -out hyin.key 2048

## 2. generate certificate request  crs
openssl req -new -key hyin.key -out hyin.csr \
        -subj "/CN=hyin/O=vert-eda"      #/O namespace 

## 3. use CA crt and key to sign hyin's cert
openssl x509 -req -in hyin.csr -CA CA/ca.crt -CAkey CA/ca.key \
        -CAcreateserial -out hyin.crt -days 360


    ##########################################
    #script for fast generate user cert:
    ##########################################
    #!/usr/bin/env bash
    # $1 - username
    # $2 - namespace
    # $3 - k8s CA directory - used for signing the user's crt
    #      CA is from target cluster
    rm -rf ./tmp
    mkdir ./tmp && cd ./tmp
    openssl genrsa -out $1.key 2048
    openssl req -new -key $1.key -out $1.csr \
            -subj "/CN=$1/O=$2"  
    openssl x509 -req -in $1.csr -CA $3/ca.crt -CAkey $3/ca.key \
            -CAcreateserial -out $1.crt -days 365


## 4. Create kubeconfig for user hyin, so hyin can visit the kubernetes cluster 

# 4.1 - this can be done by hyin by sending the crt to hyin
# 4.2 - by modifying current ~/.kube/config and sending to hyin

# 4.1 - done by hyin: need ca.crt, hyin.crt, hyin.key
kubectl --kubeconfig hyin.kubeconfig config set-cluster ?kubernetes?  \
        --server https://xx.xx.xx.xx:6443 \
        --certificate-authority=hyin.crt

...

## Add the user: hyin into the config file: hyin.kubeconfig

kubectl --kubeconfig hyin.kubeconfig config set-credentials hyin \
        --client-certificate  /home/hyin/xxx/hyin.crt \
        --client-key /home/hyin/xxx/hyin.key

## Set the context:

kubectl --kubeconfig hyin.kubeconfig set-context context-hyin \
        --cluster ?kubernetes? \
        --namespace vert-eda  \
        --user hyin

# 4.2 - by modifying current ~/.kube/config and sending to hyin
in current user env say admin:
a. cp ~/.kube/config ./tmp/
b. vi ./tmp/config        
          `cat user.crt | base64 -w0` to get the pastable crt
          `cat user.key | base64 -w0` to get user's private key
c. change cluster / user / context
d: copy to hyin
e: save as $HOST/home/hyin/.kube/config


## 5. define role (give permissions to user)

# for help
kube create role -help 

kubectl create role role-hyin \
        --verb=get,list \
        --resource=pods \
        --namespace vert-eda

# for check the configuration in yaml format
kubectl -n vert-eda get role role-hyin -o yaml


## 6. Create rolebinding 

kubectl create rolebinding rolebinding-hyin \
        --role=role-hyin  \
        --user=hyin \
        --namespace vert-eda

#using namespace as group for group policy here
kubectl create rolebinding rolebinding-hyin \
        --role=role-hyin  \
        --group=vert-eda \
        --namespace vert-eda

# check the rolebinding
kubectl -n vert-eda get rolebinding rolebinding-hyin -o yaml

###  Group the accesses for multiple users ###

## 0. more users need to visit same resources
## 1. generate key/crt for new users
## 2. ??

kubectl create rolebinding rolebinding-yourgroup \
        --role=role-hyin  \
        --group=group-vert-eda \
        --namespace vert-eda

kubectl -n vert-eda get rolebinding rolebindig-yourgroup -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding 
metaqdata:
  creationTimestamp: ....
  name: rolebinding-yourgroup
  namespace: vert-eda
  resourceVersion: "..."
  selfLink: /apis/rbac.authroization.k8s.io/v1/namespaces/vert-eda/rolebindings/rolebinding-yourgroup
  uid: ...
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-hyin
subjects:
- apiGroup: rbac.authroization.k8s.io
  kind: Group
  name: group-vert-eda

########################################################################
# Concepts
########################################################################
Role and ClusterRole

A Role always sets permissions withing a particualr namespace - when you 
create a Role, you have to specify the namespace it belongs to. 

ClusterRole - non-namespaced resource. Kubernetes objects always has to be
either namespaced or not namespaced, it can't be both. 

ClusterRoles have several uses. You can use a ClusterRole to:

 . define permissions on namespaced resources and be granted within individual 
   namespace(s)
 . define permissions on namespaced resources and be granted across all namespaces
 . define permissions on cluster-scoped resources

If you want to define a role within a namespace, use a Role; if you want to 
define a role cluster-wide, use a ClusterRole; you can use them to grant
access to:
 .cluster-scoped resources (like nodes)
 .non-resource endpoints (like /healthz)
 .namespaced resources (like Pods), across all namespaces 
   i.e.: you can use a ClusterRole to allow a particular user to run 
         `kubectl get pods --all-namespaces`.